//go:build !wasm

// DO NOT EDIT. generated by github.com/tinywasm/orm

package skill

import (
	"github.com/tinywasm/fmt"
	"github.com/tinywasm/orm"
)

func (m *cat) FormName() string {
	return "cat"
}

var _schemacat = []fmt.Field{
	{Name: "id", Type: fmt.FieldInt, PK: true, AutoInc: true},
	{Name: "name", Type: fmt.FieldText, Unique: true},
}

func (m *cat) Schema() []fmt.Field { return _schemacat }

func (m *cat) Pointers() []any {
	return []any{
		&m.ID,
		&m.Name,
	}
}

var cat_ = struct {
	TableName string
	ID        string
	Name      string
}{
	TableName: "cats",
	ID:        "id",
	Name:      "name",
}

func ReadOnecat(qb *orm.QB, model *cat) (*cat, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllcat(qb *orm.QB) ([]*cat, error) {
	var results []*cat
	err := qb.ReadAll(
		func() fmt.Model { return &cat{} },
		func(m fmt.Model) { results = append(results, m.(*cat)) },
	)
	return results, err
}

func (m *skillModel) FormName() string {
	return "skill_model"
}

var _schemaskillModel = []fmt.Field{
	{Name: "id", Type: fmt.FieldInt, PK: true, AutoInc: true},
	{Name: "cat_id", Type: fmt.FieldInt},
	{Name: "name", Type: fmt.FieldText, Unique: true},
	{Name: "info", Type: fmt.FieldText},
}

func (m *skillModel) Schema() []fmt.Field { return _schemaskillModel }

func (m *skillModel) Pointers() []any {
	return []any{
		&m.ID,
		&m.CatID,
		&m.Name,
		&m.Info,
	}
}

var skillModel_ = struct {
	TableName string
	ID        string
	CatID     string
	Name      string
	Info      string
}{
	TableName: "skills",
	ID:        "id",
	CatID:     "cat_id",
	Name:      "name",
	Info:      "info",
}

func ReadOneskillModel(qb *orm.QB, model *skillModel) (*skillModel, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllskillModel(qb *orm.QB) ([]*skillModel, error) {
	var results []*skillModel
	err := qb.ReadAll(
		func() fmt.Model { return &skillModel{} },
		func(m fmt.Model) { results = append(results, m.(*skillModel)) },
	)
	return results, err
}

func (m *paramModel) FormName() string {
	return "param_model"
}

var _schemaparamModel = []fmt.Field{
	{Name: "id", Type: fmt.FieldInt, PK: true, AutoInc: true},
	{Name: "skill_id", Type: fmt.FieldInt},
	{Name: "name", Type: fmt.FieldText},
	{Name: "type", Type: fmt.FieldText},
	{Name: "info", Type: fmt.FieldText},
	{Name: "req", Type: fmt.FieldBool},
}

func (m *paramModel) Schema() []fmt.Field { return _schemaparamModel }

func (m *paramModel) Pointers() []any {
	return []any{
		&m.ID,
		&m.SkillID,
		&m.Name,
		&m.Type,
		&m.Info,
		&m.Req,
	}
}

var paramModel_ = struct {
	TableName string
	ID        string
	SkillID   string
	Name      string
	Type      string
	Info      string
	Req       string
}{
	TableName: "params",
	ID:        "id",
	SkillID:   "skill_id",
	Name:      "name",
	Type:      "type",
	Info:      "info",
	Req:       "req",
}

func ReadOneparamModel(qb *orm.QB, model *paramModel) (*paramModel, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllparamModel(qb *orm.QB) ([]*paramModel, error) {
	var results []*paramModel
	err := qb.ReadAll(
		func() fmt.Model { return &paramModel{} },
		func(m fmt.Model) { results = append(results, m.(*paramModel)) },
	)
	return results, err
}
